### ISSUE TITLE
[Bug]: Me buses and me hatches on multiblocks from gt mod crashes

### ISSUE THREAD

**Issue by Freezo-mc** [ThePansmith/Monifactory#1041]
Description: Ticking grid on end of server tick

java.lang.RuntimeException: Slot 0 not in valid range - [0,0)
	at com.lowdragmc.lowdraglib.misc.ItemStackTransfer.validateSlotIndex(ItemStackTransfer.java:199) ~[ldlib-forge-1.20.1-1.0.28.d.jar%23463!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.misc.ItemStackTransfer.insertItem(ItemStackTransfer.java:82) ~[ldlib-forge-1.20.1-1.0.28.d.jar%23463!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.trait.NotifiableItemStackHandler.insertItem(NotifiableItemStackHandler.java:262) ~[gtceu-1.20.1-1.4.4.jar%23439!/:1.4.4] {re:classloading}
	at com.lowdragmc.lowdraglib.misc.ItemTransferList.insertItem(ItemTransferList.java:74) ~[ldlib-forge-1.20.1-1.0.28.d.jar%23463!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.misc.IOItemTransferList.insertItem(IOItemTransferList.java:35) ~[gtceu-1.20.1-1.4.4.jar%23439!/:1.4.4] {re:classloading}
	at com.lowdragmc.lowdraglib.side.item.forge.ItemTransferHelperImpl$1.insertItem(ItemTransferHelperImpl.java:42) ~[ldlib-forge-1.20.1-1.0.28.d.jar%23463!/:?] {re:classloading}
	at appeng.me.storage.ExternalStorageFacade$ItemHandlerFacade.insertExternal(ExternalStorageFacade.java:134) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.me.storage.ExternalStorageFacade.insert(ExternalStorageFacade.java:54) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.me.storage.CompositeStorage.insert(CompositeStorage.java:45) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.helpers.patternprovider.PatternProviderTargetCache$1.insert(PatternProviderTargetCache.java:66) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.helpers.patternprovider.PatternProviderLogic.adapterAcceptsAll(PatternProviderLogic.java:467) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:mixin,re:classloading,pl:mixin:APP:mixins.mae2.json:PatternProviderLogicMixin,pl:mixin:A}
	at appeng.helpers.patternprovider.PatternProviderLogic.pushPattern(PatternProviderLogic.java:1025) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:mixin,re:classloading,pl:mixin:APP:mixins.mae2.json:PatternProviderLogicMixin,pl:mixin:A}
	at appeng.crafting.execution.CraftingCpuLogic.executeCrafting(CraftingCpuLogic.java:211) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.crafting.execution.CraftingCpuLogic.tickCraftingLogic(CraftingCpuLogic.java:156) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.me.service.CraftingService.onServerEndTick(CraftingService.java:152) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.me.Grid.onServerEndTick(Grid.java:236) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.hooks.ticking.TickHandler.onServerTickEnd(TickHandler.java:325) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.hooks.ticking.TickHandler.onServerTick(TickHandler.java:299) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:950) ~[forge-1.20.1-47.3.7-universal.jar%23551!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.potential_spawns_alloc.ForgeEventFactoryMixin,pl:mixin:APP:lithium.mixins.json:collections.mob_spawning.ForgeEventFactoryMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:835) ~[client-1.20.1-20230612.114412-srg.jar%23546!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23546!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23546!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23546!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	LowDragLib (ldlib), Version: 1.0.28.d
		at TRANSFORMER/ldlib@1.0.28.d/com.lowdragmc.lowdraglib.misc.ItemStackTransfer.validateSlotIndex(ItemStackTransfer.java:199)

	Modern AE2 Additions (mae2), Version: 1.4.1
		Mixin class: stone.mae2.mixins.PatternProviderLogicMixin
		Target: appeng.helpers.patternprovider.PatternProviderLogic
		at TRANSFORMER/ae2@15.2.13/appeng.helpers.patternprovider.PatternProviderLogic.pushPattern(PatternProviderLogic.java:1025)

	Applied Energistics 2 (ae2), Version: 15.2.13
		Issue tracker URL: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues
		at TRANSFORMER/ae2@15.2.13/appeng.me.storage.ExternalStorageFacade$ItemHandlerFacade.insertExternal(ExternalStorageFacade.java:134)

	GregTech (gtceu), Version: 1.4.4
		Issue tracker URL: https://github.com/GregTechCEu/GregTech-Modern/issues/
		at TRANSFORMER/gtceu@1.4.4/com.gregtechceu.gtceu.api.machine.trait.NotifiableItemStackHandler.insertItem(NotifiableItemStackHandler.java:262)
Stacktrace:
	at com.lowdragmc.lowdraglib.misc.ItemStackTransfer.validateSlotIndex(ItemStackTransfer.java:199) ~[ldlib-forge-1.20.1-1.0.28.d.jar%23463!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.misc.ItemStackTransfer.insertItem(ItemStackTransfer.java:82) ~[ldlib-forge-1.20.1-1.0.28.d.jar%23463!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.trait.NotifiableItemStackHandler.insertItem(NotifiableItemStackHandler.java:262) ~[gtceu-1.20.1-1.4.4.jar%23439!/:1.4.4] {re:classloading}
	at com.lowdragmc.lowdraglib.misc.ItemTransferList.insertItem(ItemTransferList.java:74) ~[ldlib-forge-1.20.1-1.0.28.d.jar%23463!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.misc.IOItemTransferList.insertItem(IOItemTransferList.java:35) ~[gtceu-1.20.1-1.4.4.jar%23439!/:1.4.4] {re:classloading}
	at com.lowdragmc.lowdraglib.side.item.forge.ItemTransferHelperImpl$1.insertItem(ItemTransferHelperImpl.java:42) ~[ldlib-forge-1.20.1-1.0.28.d.jar%23463!/:?] {re:classloading}
	at appeng.me.storage.ExternalStorageFacade$ItemHandlerFacade.insertExternal(ExternalStorageFacade.java:134) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.me.storage.ExternalStorageFacade.insert(ExternalStorageFacade.java:54) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.me.storage.CompositeStorage.insert(CompositeStorage.java:45) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.helpers.patternprovider.PatternProviderTargetCache$1.insert(PatternProviderTargetCache.java:66) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.helpers.patternprovider.PatternProviderLogic.adapterAcceptsAll(PatternProviderLogic.java:467) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:mixin,re:classloading,pl:mixin:APP:mixins.mae2.json:PatternProviderLogicMixin,pl:mixin:A}
	at appeng.helpers.patternprovider.PatternProviderLogic.pushPattern(PatternProviderLogic.java:1025) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:mixin,re:classloading,pl:mixin:APP:mixins.mae2.json:PatternProviderLogicMixin,pl:mixin:A}
	at appeng.crafting.execution.CraftingCpuLogic.executeCrafting(CraftingCpuLogic.java:211) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.crafting.execution.CraftingCpuLogic.tickCraftingLogic(CraftingCpuLogic.java:156) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.me.service.CraftingService.onServerEndTick(CraftingService.java:152) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.me.Grid.onServerEndTick(Grid.java:236) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
-- Grid being ticked --
Details:
	Nodes: 244
	Serial number: 263
	Node: node@2d06c170 hosted by appeng.parts.networking.GlassCablePart @ -503,65,40
	Part Side: ~~NULL~~
	Name: ae2:cable_bus // appeng.blockentity.networking.CableBusBlockEntity
	Block: CableBusBlock[cable_bus][light_level=0,waterlogged=false]
	Block location: World: (-503,65,40), Section: (at 9,1,8 in -32,4,2; chunk contains blocks -512,-64,32 to -497,319,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Block: CableBusBlock[cable_bus][light_level=0,waterlogged=false]
	Block location: World: (-503,65,40), Section: (at 9,1,8 in -32,4,2; chunk contains blocks -512,-64,32 to -497,319,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Block Entity NBT: {ForgeCaps:{},cable:{gn:{e:25.0d,p:0},id:"ae2:fluix_glass_cable"},hasRedstone:2}
	Level: ResourceKey[minecraft:dimension / minecraft:overworld]
Stacktrace:
	at appeng.hooks.ticking.TickHandler.onServerTickEnd(TickHandler.java:325) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at appeng.hooks.ticking.TickHandler.onServerTick(TickHandler.java:299) ~[appliedenergistics2-forge-15.2.13.jar%23357!/:15.2.13] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:950) ~[forge-1.20.1-47.3.7-universal.jar%23551!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.potential_spawns_alloc.ForgeEventFactoryMixin,pl:mixin:APP:lithium.mixins.json:collections.mob_spawning.ForgeEventFactoryMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:835) ~[client-1.20.1-20230612.114412-srg.jar%23546!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23546!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23546!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23546!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}
Crash Report UUID: 51468a62-9c9e-40d9-b326-539a0d76c795
	FML: 47.3
	Forge: net.minecraftforge:47.3.7
	Flywheel Backend: Parallel Batching
	Suspected Mods: Modern AE2 Additions (mae2), Forge (forge), Applied Energistics 2 (ae2), Minecraft (minecraft), LowDragLib (ldlib), GregTech (gtceu)

**Comment by ThePansmith** [comment]
Is this a moni issue or a GT issue?

**Comment by Freezo-mc** [comment]
Nevermind it's working in a newer version of moni it didn't work at 0.9.5.

pi 1. 11. 2024 o 18:49 Pansmith ***@***.***> napísal(a):
