### ISSUE TITLE
[Bug]: crash when trying to change robot arm settings

### ISSUE THREAD

**Issue by MrRofl93** [ThePansmith/Monifactory#1128]
### Issue Summary

Pack version 0.10.1
When going to the input/output settings of a machine and click a surface where the robot arm is and click on the settings of the robot arm, it logs me out of single player and it shows me the server list.

This is similar too this issue: https://github.com/ThePansmith/Monifactory/issues/1124

### Reproduction steps

1. place gregtech machine down
2. right click the machine
3. open input/output settings of the machine
4. click a side 
5. add a robot arm to that side
6. click on robot arm settings
[crash-2024-11-15_18.52.29-server.txt](https://github.com/user-attachments/files/17780072/crash-2024-11-15_18.52.29-server.txt)

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Embeddium instance tainted by mods: [betterfpsdist, gtceu, oculus, bocchium, culllessleaves]
// Please do not reach out for Embeddium support without removing these mods first.
// -------
// You're mean.

Time: 2024-11-15 18:52:29
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.textSupplier" is null
	at com.lowdragmc.lowdraglib.gui.widget.LabelWidget.detectAndSendChanges(LabelWidget.java:132) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.detectAndSendChanges(WidgetGroup.java:487) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.detectAndSendChanges(WidgetGroup.java:487) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.detectAndSendChanges(WidgetGroup.java:487) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.detectAndSendChanges(WidgetGroup.java:487) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.gui.fancy.ConfiguratorPanel$Tab.detectAndSendChanges(ConfiguratorPanel.java:237) ~[gtceu-1.20.1-1.5.1.jar%23444!/:1.5.1] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.detectAndSendChanges(WidgetGroup.java:487) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.detectAndSendChanges(WidgetGroup.java:487) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.detectAndSendChanges(WidgetGroup.java:487) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.modular.ModularUIContainer.m_38946_(ModularUIContainer.java:98) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayer.m_8119_(ServerPlayer.java:435) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forgivingvoid.mixins.json:ServerPlayerAccessor,pl:mixin:APP:ldlib-common.mixins.json:accessor.ServerPlayerAccessor,pl:mixin:APP:kubejs-common.mixins.json:ServerPlayerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.ServerWorldAccessor,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:gcyr.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:lithium.mixins.json:entity.collisions.intersection.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_entity_retrieval.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_tracking.block_listening.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_block_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_height.WorldMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:gtceu.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.ServerWorldAccessor,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:gcyr.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithium.mixins.json:collections.entity_ticking.EntityListMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.ServerWorldAccessor,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:gcyr.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	LowDragLib (ldlib), Version: 1.0.32.a
		at TRANSFORMER/ldlib@1.0.32.a/com.lowdragmc.lowdraglib.gui.widget.LabelWidget.detectAndSendChanges(LabelWidget.java:132)

	GregTech (gtceu), Version: 1.5.1
		Issue tracker URL: https://github.com/GregTechCEu/GregTech-Modern/issues/
		at TRANSFORMER/gtceu@1.5.1/com.gregtechceu.gtceu.api.gui.fancy.ConfiguratorPanel$Tab.detectAndSendChanges(ConfiguratorPanel.java:237)
Stacktrace:
	at com.lowdragmc.lowdraglib.gui.widget.LabelWidget.detectAndSendChanges(LabelWidget.java:132) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.detectAndSendChanges(WidgetGroup.java:487) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.detectAndSendChanges(WidgetGroup.java:487) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.detectAndSendChanges(WidgetGroup.java:487) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.detectAndSendChanges(WidgetGroup.java:487) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.gui.fancy.ConfiguratorPanel$Tab.detectAndSendChanges(ConfiguratorPanel.java:237) ~[gtceu-1.20.1-1.5.1.jar%23444!/:1.5.1] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.detectAndSendChanges(WidgetGroup.java:487) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.detectAndSendChanges(WidgetGroup.java:487) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.detectAndSendChanges(WidgetGroup.java:487) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.modular.ModularUIContainer.m_38946_(ModularUIContainer.java:98) ~[ldlib-forge-1.20.1-1.0.32.a.jar%23468!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayer.m_8119_(ServerPlayer.java:435) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forgivingvoid.mixins.json:ServerPlayerAccessor,pl:mixin:APP:ldlib-common.mixins.json:accessor.ServerPlayerAccessor,pl:mixin:APP:kubejs-common.mixins.json:ServerPlayerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.ServerWorldAccessor,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:gcyr.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:lithium.mixins.json:entity.collisions.intersection.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_entity_retrieval.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_tracking.block_listening.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_block_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_height.WorldMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:gtceu.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.ServerWorldAccessor,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:gcyr.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithium.mixins.json:collections.entity_ticking.EntityListMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.ServerWorldAccessor,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:gcyr.mixins.json:ServerLevelMixin,pl:mixin:A}
-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.ServerPlayer)
	Entity ID: 2735
	Entity Name: MrRofl93
	Entity's Exact location: -397.10, 83.00, -200.38
	Entity's Block location: World: (-398,83,-201), Section: (at 2,3,7 in -25,5,-13; chunk contains blocks -400,-64,-208 to -385,319,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Air:300s,Attributes:[{Base:0.10000000149011612d,Name:"minecraft:generic.movement_speed"},{Base:0.0d,Name:"minecraft:generic.knockback_resistance"},{Base:4.5d,Name:"forge:block_reach"},{Base:20.0d,Name:"minecraft:generic.max_health"},{Base:0.0d,Name:"forge:step_height_addition"},{Base:0.08d,Name:"forge:entity_gravity"}],BalmData:{WaystonesData:{Waystones:[]}},Brain:{memories:{}},CanUpdate:1b,DataVersion:3465,DeathTime:0s,Dimension:"minecraft:overworld",EnderItems:[],FallDistance:0.0f,FallFlying:0b,Fire:-20s,ForgeCaps:{"curios:inventory":{Curios:[{Identifier:"head",StacksHandler:{Cosmetics:{Items:[],Size:1},DropRule:"DEFAULT",HasCosmetic:0b,RenderToggle:1b,Renders:{Renders:[{Render:1b,Slot:0}],Size:1},SavedBaseSize:1,Stacks:{Items:[],Size:1},Visible:1b}},{Identifier:"back",StacksHandler:{Cosmetics:{Items:[],Size:1},DropRule:"DEFAULT",HasCosmetic:0b,RenderToggle:1b,Renders:{Renders:[{Render:1b,Slot:0}],Size:1},SavedBaseSize:1,Stacks:{Items:[],Size:1},Visible:1b}},{Identifier:"body",StacksHandler:{Cosmetics:{Items:[],Size:1},DropRule:"DEFAULT",HasCosmetic:0b,RenderToggle:1b,Renders:{Renders:[{Render:1b,Slot:0}],Size:1},SavedBaseSize:1,Stacks:{Items:[],Size:1},Visible:1b}},{Identifier:"hands",StacksHandler:{Cosmetics:{Items:[],Size:1},DropRule:"DEFAULT",HasCosmetic:0b,RenderToggle:1b,Renders:{Renders:[{Render:1b,Slot:0}],Size:1},SavedBaseSize:1,Stacks:{Items:[],Size:1},Visible:1b}},{Identifier:"belt",StacksHandler:{Cosmetics:{Items:[],Size:1},DropRule:"DEFAULT",HasCosmetic:0b,RenderToggle:1b,Renders:{Renders:[{Render:1b,Slot:0}],Size:1},SavedBaseSize:1,Stacks:{Items:[],Size:1},Visible:1b}},{Identifier:"charm",StacksHandler:{Cosmetics:{Items:[],Size:1},DropRule:"DEFAULT",HasCosmetic:0b,RenderToggle:1b,Renders:{Renders:[{Render:1b,Slot:0}],Size:1},SavedBaseSize:1,Stacks:{Items:[],Size:1},Visible:1b}},{Identifier:"gtceu_magnet",StacksHandler:{Cosmetics:{Items:[],Size:1},DropRule:"DEFAULT",HasCosmetic:0b,RenderToggle:0b,Renders:{Renders:[{Render:1b,Slot:0}],Size:1},SavedBaseSize:1,Stacks:{Items:[],Size:1},Visible:1b}},{Identifier:"angel_ring",StacksHandler:{Cosmetics:{Items:[],Size:1},DropRule:"DEFAULT",HasCosmetic:0b,RenderToggle:1b,Renders:{Renders:[{Render:1b,Slot:0}],Size:1},SavedBaseSize:1,Stacks:{Items:[],Size:1},Visible:1b}},{Identifier:"deep_learner",StacksHandler:{Cosmetics:{Items:[],Size:1},DropRule:"DEFAULT",HasCosmetic:0b,RenderToggle:0b,Renders:{Renders:[{Render:1b,Slot:0}],Size:1},SavedBaseSize:1,Stacks:{Items:[],Size:1},Visible:1b}},{Identifier:"hook",StacksHandler:{Cosmetics:{Items:[],Size:1},DropRule:"DEFAULT",HasCosmetic:0b,RenderToggle:1b,Renders:{Renders:[{Render:1b,Slot:0}],Size:1},SavedBaseSize:1,Stacks:{Items:[],Size:1},Visible:1b}}]},"gtceu:medical_condition_tracker":{medical_conditions:[],permanent_conditions:[]},"hangglider:gliding":{GliderDeployed:0b,Gliding:0b},"ironfurnaces:furnaces_list":{count:0,furnaces:{}},"ironfurnaces:show_config":{show:0},"lostcities:spawnset":{spawnSet:1b},"nuclearcraft:radiation":{radiation:0,timestamp:0},"polymorph:player_recipe_data":{},"shrink:shrunk":{defaulteyeheight:0.0f,fixed:0b,height:0.0f,isshrinking:0b,isshrunk:0b,scale:1.0f,width:0.0f},"toolbelt:belt_slot":{Items:[],Size:1}},ForgeData:{PlayerPersisted:{BalmData:{WaystonesData:{Waystones:[]}}}},Health:20.0f,HurtByTimestamp:0,HurtTime:0s,Inventory:[{Count:1b,Slot:0b,id:"gtceu:lv_1a_energy_converter"},{Count:1b,Slot:1b,id:"gtceu:lv_cutter"},{Count:1b,Slot:3b,id:"steamdynamo:steam_dynamo"},{Count:1b,Slot:4b,id:"watercollector:watercollector"},{Count:64b,Slot:5b,id:"gtceu:tin_single_wire"},{Count:57b,Slot:9b,id:"minecraft:emerald"},{Count:12b,Slot:12b,id:"minecraft:glowstone"},{Count:12b,Slot:13b,id:"minecraft:lapis_lazuli"},{Count:22b,Slot:14b,id:"minecraft:redstone"},{Count:64b,Slot:16b,id:"minecraft:emerald"},{Count:64b,Slot:17b,id:"minecraft:emerald"},{Count:64b,Slot:18b,id:"minecraft:emerald"},{Count:64b,Slot:19b,id:"minecraft:emerald"},{Count:64b,Slot:20b,id:"minecraft:emerald"},{Count:64b,Slot:21b,id:"minecraft:emerald"},{Count:64b,Slot:22b,id:"minecraft:emerald"},{Count:64b,Slot:23b,id:"minecraft:emerald"},{Count:64b,Slot:24b,id:"minecraft:emerald"},{Count:64b,Slot:25b,id:"minecraft:emerald"},{Count:64b,Slot:26b,id:"minecraft:emerald"},{Count:64b,Slot:27b,id:"minecraft:emerald"},{Count:64b,Slot:28b,id:"minecraft:emerald"},{Count:64b,Slot:29b,id:"minecraft:emerald"},{Count:64b,Slot:30b,id:"minecraft:emerald"},{Count:64b,Slot:31b,id:"minecraft:emerald"},{Count:64b,Slot:32b,id:"minecraft:emerald"},{Count:64b,Slot:33b,id:"minecraft:emerald"},{Count:64b,Slot:34b,id:"minecraft:emerald"},{Count:64b,Slot:35b,id:"minecraft:emerald"}],Invulnerable:0b,Motion:[0.0d,-0.0784000015258789d,0.0d],OnGround:1b,PortalCooldown:0,Pos:[-397.1043521753755d,83.0d,-200.3806576009795d],Rotation:[-8.700073f,7.1999607f],Score:183,SelectedItemSlot:1,SleepTimer:0s,SpawnAngle:0.0f,SpawnDimension:"minecraft:overworld",SpawnForced:1b,SpawnX:-397,SpawnY:83,SpawnZ:-208,Tags:["mode_normal","starting_items"],UUID:[I;453666810,1971997738,-1141119511,2060282095],XpLevel:10,XpP:0.85185176f,XpSeed:670986277,XpTotal:183,abilities:{flySpeed:0.05f,flying:0b,instabuild:1b,invulnerable:1b,mayBuild:1b,mayfly:1b,walkSpeed:0.1f},foodExhaustionLevel:0.0f,foodLevel:20,foodSaturationLevel:5.0f,foodTickTimer:0,"gcyr:gps_tracked":0b,playerGameType:1,recipeBook:{},seenCredits:0b,warden_spawn_tracker:{cooldown_ticks:0,ticks_since_last_warning:7728,warning_level:0}}
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:lithium.mixins.json:entity.collisions.intersection.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_entity_retrieval.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_tracking.block_listening.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_block_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_height.WorldMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:gtceu.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.ServerWorldAccessor,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:gcyr.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithium.mixins.json:collections.entity_ticking.EntityListMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.ServerWorldAccessor,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:gcyr.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23554!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
```

**Comment by MrRofl93** [comment]
Is fixed Pack version 0.10.2. Thanks
