### ISSUE TITLE
[Bug]: Redirector breaks many mods

### ISSUE THREAD

**Issue by TelepathicGrunt** [ThePansmith/Monifactory#1268]
### Issue Summary

Using Redirector will break Repurposed Structures and many other mods. Here is one issue report I have gotten using this modpack:
https://github.com/TelepathicGrunt/RepurposedStructures/issues/358

Redirector is known to cause cursed issues with enums and other mods. Its idea is noble but I both strongly doubt Enums are the bottleneck of the game and the entire concept of the mod is unsafe in Java. Specifically that it assumes `Enum.values()` never needs to clone the arrays returned so it caches that list for many enums in the game. Which is wrong. So with redirector on, that means every single mod calling `Enum.values()` means they all get the exact same cached instance of the list. So if someone calls `.values()` later on that same enum another mod modified the list of thinking `values` was cloned, they will explode as they now get a value they were not expecting to exist as a side effect of Redirector.

`Enum.values()` must ALWAYS clone the list to be safe. Therefore Redirector cannot make that change safely and thus, having it in your mod is going to continue to generate bug reports to me and other modders. Please remove Redirector.

### Reproduction steps

Go around the world and when Repurposed Structures's dungeons spawn, there is a chance it can blow up because of redirector. See above issue report for an example case.

### Relevant log output

```shell
Caused by: java.lang.IllegalArgumentException: Cannot set property DirectionProperty{name=facing, clazz=class net.minecraft.core.Direction, values=[north, south, west, east]} to up on Block{minecraft:chest}, it is not an allowed value
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23670!/:?]
	at com.telepathicgrunt.repurposedstructures.utils.GeneralUtils.orientateChest(GeneralUtils.java:111) ~[repurposed_structures-7.1.15+1.20.1-forge.jar%23604!/:?]
	at com.telepathicgrunt.repurposedstructures.world.features.NbtDungeon.spawnLootBlocks(NbtDungeon.java:295) ~[repurposed_structures-7.1.15+1.20.1-forge.jar%23604!/:?]
	at com.telepathicgrunt.repurposedstructures.world.features.NbtDungeon.m_142674_(NbtDungeon.java:167) ~[repurposed_structures-7.1.15+1.20.1-forge.jar%23604!/:?]
	at net.minecraft.world.level.levelgen.feature.Feature.m_225028_(Feature.java:155) ~[client-1.20.1-20230612.114412-srg.jar%23670!/:?]
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_224953_(ConfiguredFeature.java:28) ~[client-1.20.1-20230612.114412-srg.jar%23670!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226362_(PlacedFeature.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23670!/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226368_(PlacedFeature.java:53) ~[client-1.20.1-20230612.114412-srg.jar%23670!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226377_(PlacedFeature.java:42) ~[client-1.20.1-20230612.114412-srg.jar%23670!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:357) ~[client-1.20.1-20230612.114412-srg.jar%23670!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108) ~[client-1.20.1-20230612.114412-srg.jar%23670!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309) ~[client-1.20.1-20230612.114412-srg.jar%23670!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252) ~[client-1.20.1-20230612.114412-srg.jar%23670!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[client-1.20.1-20230612.114412-srg.jar%23670!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%23114!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23670!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 11 more
```

**Comment by ThePansmith** [comment]
Report to mod devs

**Comment by TelepathicGrunt** [comment]
Report to mod devs? I am the mod dev of repurposed structures and I am telling you redirector 5.0.0 breaks my mod and causing people to make bug reports to me due to your modpack. I did already report to redirector dev and they said to downgrade to 4.0.0 since their global asm enum values code is in 5.0.0.
