### ISSUE TITLE
Mods being packaged into the wrong release files

### ISSUE THREAD

**Issue by JuiceyBeans** [ThePansmith/Monifactory#177]
A lot of mods are being packaged into the wrong packs (client/server) on release and may cause potential issues

Server only:
- FTB Quests Optimizer

Client only:
- Embeddium
- Embeddium++
- Zume
- WATERMeDIA

Will update if I find more

**Comment by ThePansmith** [comment]
@LetterN

**Comment by hgjensen** [comment]
This is still relevant. Just updated to 0.2.5 with server.zip. Server crash on start because of client-only mods like drippyloadingscreen

**Comment by arctair** [comment]
[Release 0.2.6](https://github.com/ThePansmith/Monifactory/releases/tag/0.2.6) server fails to start

`/server/crash-reports/crash-2024-05-14_19.40.41-fml.txt`
```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mods: NONE
Stacktrace:
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
-- MOD citresewn --
Details:
        Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/atlas/SpriteSource
```

**Comment by hgjensen** [comment]
> [Release 0.2.6](https://github.com/ThePansmith/Monifactory/releases/tag/0.2.6) server fails to start
> 
> `/server/crash-reports/crash-2024-05-14_19.40.41-fml.txt`
> 
> ```
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: main
> Suspected Mods: NONE
> Stacktrace:
>         at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
> -- MOD citresewn --
> Details:
>         Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/atlas/SpriteSource
> ```

Remove citresewn-1.20.1-5.jar from server. It is a client-only mod afaik
