### ISSUE TITLE
[Bug]: NuclearcraftRecipe Server<->Client mismatch

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [ThePansmith/Monifactory#291]
### Issue Summary

Can't connect to server due to 3 recipes failing to load properly? Not sure.

The log output below makes it so that I can't connect due to a recipe mismatch between client and server
EDIT: Can provide full logs in a private message, as it contains IP addresses.

### Reproduction steps

1. Download latest version
2. Make a server using reccomended forge
3. Switched to hard mode on both client and server

### Relevant log output

```shell
[11:20:14] [WARN] Failed to parse recipe 'nuclearcraft:patchouli_book[minecraft:crafting_shapeless]'! Falling back to vanilla: ItemStack 'result' can't be empty!
[11:20:14] [WARN] Failed to parse recipe 'chipped_express:stonecutting_chipped_course_sand_from_sand[minecraft:stonecutting]'! Falling back to vanilla: ItemStack 'result' can't be empty!
[11:20:14] [WARN] Failed to parse recipe 'armorplus:crafting/shapeless/patchouli/ap_book[minecraft:crafting_shapeless]'! Falling back to vanilla: ItemStack 'result' can't be empty!



[03Jun2024 11:22:41.084] [Netty Epoll Server IO #5/ERROR] [igentuman.nc.NuclearCraft/]: Error writing recipe to packet.
java.lang.IllegalArgumentException: FluidStackIngredients cannot be created using the empty stack.
	at igentuman.nc.recipes.ingredient.creator.FluidStackIngredientCreator.from(FluidStackIngredientCreator.java:42) ~[NuclearCraft-1.20.1-1.0.0-beta.6.jar%23423!/:1.0.0-beta.6]
	at igentuman.nc.recipes.ingredient.creator.FluidStackIngredientCreator.from(FluidStackIngredientCreator.java:30) ~[NuclearCraft-1.20.1-1.0.0-beta.6.jar%23423!/:1.0.0-beta.6]
	at igentuman.nc.recipes.type.NcRecipe.getEmptyFluid(NcRecipe.java:81) ~[NuclearCraft-1.20.1-1.0.0-beta.6.jar%23423!/:1.0.0-beta.6]
	at igentuman.nc.recipes.type.NcRecipe.write(NcRecipe.java:114) ~[NuclearCraft-1.20.1-1.0.0-beta.6.jar%23423!/:1.0.0-beta.6]
	at igentuman.nc.recipes.serializers.NcRecipeSerializer.toNetwork(NcRecipeSerializer.java:193) ~[NuclearCraft-1.20.1-1.0.0-beta.6.jar%23423!/:1.0.0-beta.6]
	at igentuman.nc.recipes.serializers.NcRecipeSerializer.m_6178_(NcRecipeSerializer.java:26) ~[NuclearCraft-1.20.1-1.0.0-beta.6.jar%23423!/:1.0.0-beta.6]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_179469_(ClientboundUpdateRecipesPacket.java:52) ~[server-1.20.1-20230612.114412-srg.jar%23483!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_236828_(FriendlyByteBuf.java:221) ~[server-1.20.1-20230612.114412-srg.jar%23483!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_5779_(ClientboundUpdateRecipesPacket.java:27) ~[server-1.20.1-20230612.114412-srg.jar%23483!/:?]
	at net.minecraftforge.network.filters.VanillaPacketSplitter.appendPackets(VanillaPacketSplitter.java:66) ~[forge-1.20.1-47.2.32-universal.jar%23488!/:?]
	at net.minecraftforge.network.filters.ForgeConnectionNetworkFilter.splitPacket(ForgeConnectionNetworkFilter.java:62) ~[forge-1.20.1-47.2.32-universal.jar%23488!/:?]
	at net.minecraftforge.network.filters.VanillaPacketFilter.encode(VanillaPacketFilter.java:60) ~[forge-1.20.1-47.2.32-universal.jar%23488!/:?]
	at net.minecraftforge.network.filters.VanillaPacketFilter.encode(VanillaPacketFilter.java:23) ~[forge-1.20.1-47.2.32-universal.jar%23488!/:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.82.Final.jar%2381!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at net.minecraft.network.Connection.m_243087_(Connection.java:224) ~[server-1.20.1-20230612.114412-srg.jar%23483!/:?]
	at net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:213) ~[server-1.20.1-20230612.114412-srg.jar%23483!/:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar%2382!/:4.1.82.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar%2382!/:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar%2382!/:4.1.82.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.82.Final.jar%2386!/:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar%2382!/:4.1.82.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar%2382!/:4.1.82.Final]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by 3x1t-5tyl3** [comment]
Closing this. This seems still like a critical issue, but rebooting the server seemed to fix it. New installs will reproduce this bug however.

**Comment by ThePansmith** [comment]
Seems like a NC issue? Report to them.
