### ISSUE TITLE
[Bug]: Generating a superflat world causes the game to crash

### ISSUE THREAD

**Issue by zbigniewzolnierowicz** [ThePansmith/Monifactory#432]
### Issue Summary

Attempting to generate a superflat world crashes the game at roughly 65%, due to Lost Cities being unable to find a valid spawn position.

### Reproduction steps

1. Open Singleplayer
2. Create a new world of type Superflat
3. Wait.
4. At around 65%, the game should crash.

### Relevant log output

```shell
java.lang.RuntimeException: Can't find a valid spawn position!
	at mcjty.lostcities.setup.ForgeEventHandlers.findSafeSpawnPoint(ForgeEventHandlers.java:265) ~[lostcities-1.20-7.1.6.jar%23463!/:1.20-7.1.6] {re:classloading}
	at mcjty.lostcities.setup.ForgeEventHandlers.onCreateSpawnPoint(ForgeEventHandlers.java:209) ~[lostcities-1.20-7.1.6.jar%23463!/:1.20-7.1.6] {re:classloading}
	at mcjty.lostcities.setup.__ForgeEventHandlers_onCreateSpawnPoint_CreateSpawnPosition.invoke(.dynamic) ~[lostcities-1.20-7.1.6.jar%23463!/:1.20-7.1.6] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23127!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onCreateWorldSpawn(ForgeEventFactory.java:566) ~[forge-1.20.1-47.2.21-universal.jar%23549!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177896_(MinecraftServer.java:392) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:346) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:308) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:63) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}
```

**Comment by ThePansmith** [comment]
Known Lost Cities Issue, remove the mod to generate a superflat
