### ISSUE TITLE
[Bug]: Can't connect to server on 0.8.2

### ISSUE THREAD

**Issue by hgjensen** [ThePansmith/Monifactory#689]
### Issue Summary

After upgrading server and client from 0.8.1 to 0.8.2, I can no longer connect to the server.

### Reproduction steps

Upgrade existing server and client from 0.8.1 to 0.8.2
Connect to the server.

### Relevant log output

```shell
No errors on the server.


Error message on the client:
[05:19:48] [Netty Client IO #3/WARN] [ne.mi.ne.fi.VanillaPacketSplitter/]: forge:split received out of order - inbound buffer not empty when receiving first
[05:19:48] [Netty Client IO #3/ERROR] [ig.nc.NuclearCraft/]: Error reading recipe from packet.
java.lang.IllegalArgumentException: ItemStackIngredients cannot be created using the empty ingredient.
	at igentuman.nc.recipes.ingredient.creator.ItemStackIngredientCreator.from(ItemStackIngredientCreator.java:46) ~[NuclearCraft-1.20.1-1.0.0-rc.2.jar%23484!/:1.0.0-rc.2] {re:classloading}
	at igentuman.nc.recipes.ingredient.creator.ItemStackIngredientCreator.read(ItemStackIngredientCreator.java:57) ~[NuclearCraft-1.20.1-1.0.0-rc.2.jar%23484!/:1.0.0-rc.2] {re:classloading}
	at igentuman.nc.recipes.ingredient.creator.ItemStackIngredientCreator.read(ItemStackIngredientCreator.java:33) ~[NuclearCraft-1.20.1-1.0.0-rc.2.jar%23484!/:1.0.0-rc.2] {re:classloading}
	at igentuman.nc.recipes.serializers.NcRecipeSerializer.readIngredients(NcRecipeSerializer.java:163) ~[NuclearCraft-1.20.1-1.0.0-rc.2.jar%23484!/:1.0.0-rc.2] {re:classloading}
	at igentuman.nc.recipes.serializers.NcRecipeSerializer.fromNetwork(NcRecipeSerializer.java:186) ~[NuclearCraft-1.20.1-1.0.0-rc.2.jar%23484!/:1.0.0-rc.2] {re:classloading}
	at igentuman.nc.recipes.serializers.NcRecipeSerializer.m_8005_(NcRecipeSerializer.java:27) ~[NuclearCraft-1.20.1-1.0.0-rc.2.jar%23484!/:1.0.0-rc.2] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_133647_(ClientboundUpdateRecipesPacket.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:classloading}
	at net.minecraft.network.FriendlyByteBuf.m_236838_(FriendlyByteBuf.java:211) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins/common/nochatreports.mixins.json:common.MixinFriendlyByteBuf,pl:mixin:A}
	at net.minecraft.network.FriendlyByteBuf.m_236845_(FriendlyByteBuf.java:227) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins/common/nochatreports.mixins.json:common.MixinFriendlyByteBuf,pl:mixin:A}
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.<init>(ClientboundUpdateRecipesPacket.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:classloading}
	at net.minecraft.network.ConnectionProtocol$PacketSet.m_178327_(ConnectionProtocol.java:459) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.network.ConnectionProtocol.m_178321_(ConnectionProtocol.java:522) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:classloading,pl:accesstransformer:B,pl:redirector:A}
	at net.minecraftforge.network.filters.VanillaPacketSplitter.onClientPacket(VanillaPacketSplitter.java:143) ~[forge-1.20.1-47.3.7-universal.jar%23549!/:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.20.1-47.3.7-universal.jar%23549!/:?] {re:classloading}
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:80) ~[forge-1.20.1-47.3.7-universal.jar%23549!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:core.NetworkHooksMixin,pl:mixin:A}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:80) ~[forge-1.20.1-47.3.7-universal.jar%23549!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:core.NetworkHooksMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_7413_(ClientPacketListener.java:1863) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:57) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:ClientBoundCustomPayloadPacketLMixin,pl:mixin:APP:connectivity.mixins.json:networkstats.SCustomPayloadPlayPacketNameMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:7) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:ClientBoundCustomPayloadPacketLMixin,pl:mixin:APP:connectivity.mixins.json:networkstats.SCustomPayloadPlayPacketNameMixin,pl:mixin:A}
	at net.minecraft.network.Connection.m_129517_(Connection.java:174) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:AdvancedPacketErrorLogging,pl:mixin:APP:badpackets.mixins.json:MixinConnection,pl:mixin:APP:mixins/forge/nochatreports-forge.mixins.json:client.MixinClientConnection,pl:mixin:APP:connectivity.mixins.json:ConnectionErrorMixin,pl:mixin:APP:connectivity.mixins.json:NetworkManagerMixin,pl:mixin:A}
	at net.minecraft.network.Connection.channelRead0(Connection.java:159) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:AdvancedPacketErrorLogging,pl:mixin:APP:badpackets.mixins.json:MixinConnection,pl:mixin:APP:mixins/forge/nochatreports-forge.mixins.json:client.MixinClientConnection,pl:mixin:APP:connectivity.mixins.json:ConnectionErrorMixin,pl:mixin:APP:connectivity.mixins.json:NetworkManagerMixin,pl:mixin:A}
	at net.minecraft.network.Connection.channelRead0(Connection.java:50) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:AdvancedPacketErrorLogging,pl:mixin:APP:badpackets.mixins.json:MixinConnection,pl:mixin:APP:mixins/forge/nochatreports-forge.mixins.json:client.MixinClientConnection,pl:mixin:APP:connectivity.mixins.json:ConnectionErrorMixin,pl:mixin:APP:connectivity.mixins.json:NetworkManagerMixin,pl:mixin:A}
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {re:mixin,re:computing_frames}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {re:mixin}
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {re:mixin}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {re:mixin}
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {re:mixin}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {re:mixin}
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {re:mixin}
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {re:mixin}
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {re:mixin}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar%23117!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar%23116!/:4.1.82.Final] {}
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar%23116!/:4.1.82.Final] {}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}
[05:19:48] [Netty Client IO #3/WARN] [co.co.Connectivity/]: Packet not registered: ClientboundDisconnectPacket
[05:19:48] [Netty Client IO #3/WARN] [co.co.Connectivity/]: Packet:ClientboundDisconnectPacket 
[05:19:48] [Netty Client IO #3/WARN] [co.co.Connectivity/]: Packet data:
{
  "f_132075_": "translation{key='disconnect.genericReason', args=[Internal Exception: java.lang.IllegalArgumentException: ItemStackIngredients cannot be created using the empty ingredient.]}"
}
```

**Comment by three-fold** [comment]
I'm getting exactly the same error trying to connect to a 0.8.2 server.
