### ISSUE TITLE
[Bug]: Server crashes when Functional Storage drawer is placed in world

### ISSUE THREAD

**Issue by blushymostly** [ThePansmith/Monifactory#871]
### Issue Summary

Whatever you place any drawer server crashes. After reboot drawer block is corrupted and can't be removed without another crash.

[crash-2024-10-07_14.27.43-server.txt](https://github.com/user-attachments/files/17277732/crash-2024-10-07_14.27.43-server.txt)

### Reproduction steps

1. Place any drawer in world.

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2024-10-07 14:27:43
Description: Exception in server tick loop

java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398) ~[?:?] {}
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?] {}
	at java.lang.System.load(System.java:1957) ~[?:?] {re:mixin}
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285) ~[?:?] {}
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403) ~[?:?] {}
	at java.lang.Runtime.loadLibrary0(Runtime.java:818) ~[?:?] {}
	at java.lang.System.loadLibrary(System.java:1993) ~[?:?] {re:mixin}
	at java.awt.Toolkit$2.run(Toolkit.java:1388) ~[?:?] {}
	at java.awt.Toolkit$2.run(Toolkit.java:1386) ~[?:?] {}
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?] {}
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1385) ~[?:?] {}
	at java.awt.Toolkit.initStatic(Toolkit.java:1423) ~[?:?] {}
	at java.awt.Toolkit.<clinit>(Toolkit.java:1397) ~[?:?] {}
	at java.awt.Color.<clinit>(Color.java:277) ~[?:?] {}
	at com.buuz135.functionalstorage.item.ConfigurationToolItem$ConfigurationAction.<clinit>(ConfigurationToolItem.java:113) ~[functionalstorage-1.20.1-1.2.12.jar%23374!/:1.20.1-1.2.12] {re:classloading,pl:redirector:A}
	at com.buuz135.functionalstorage.block.tile.ControllableDrawerTile$DrawerOptions.<init>(ControllableDrawerTile.java:334) ~[functionalstorage-1.20.1-1.2.12.jar%23374!/:1.20.1-1.2.12] {re:classloading}
	at com.buuz135.functionalstorage.block.tile.ControllableDrawerTile.<init>(ControllableDrawerTile.java:58) ~[functionalstorage-1.20.1-1.2.12.jar%23374!/:1.20.1-1.2.12] {re:classloading,pl:runtimedistcleaner:A}
	at com.buuz135.functionalstorage.block.tile.ItemControllableDrawerTile.<init>(ItemControllableDrawerTile.java:43) ~[functionalstorage-1.20.1-1.2.12.jar%23374!/:1.20.1-1.2.12] {re:classloading,pl:runtimedistcleaner:A}
	at com.buuz135.functionalstorage.block.tile.DrawerTile.<init>(DrawerTile.java:38) ~[functionalstorage-1.20.1-1.2.12.jar%23374!/:1.20.1-1.2.12] {re:classloading,pl:runtimedistcleaner:A}
	at com.buuz135.functionalstorage.block.DrawerBlock.lambda$getTileEntityFactory$15(DrawerBlock.java:155) ~[functionalstorage-1.20.1-1.2.12.jar%23374!/:1.20.1-1.2.12] {re:classloading}
	at com.hrznstudio.titanium.block.BasicTileBlock.m_142194_(BasicTileBlock.java:92) ~[titanium-1.20.1-3.8.32.jar%23466!/:3.8.32] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:world.inline_block_access.WorldChunkMixin,pl:mixin:APP:mixins.hammerlib.json:LevelChunkMixin,pl:mixin:APP:lithium.mixins.json:collections.block_entity_tickers.WorldChunkMixin,pl:mixin:APP:lithium.mixins.json:world.combined_heightmap_update.WorldChunkMixin,pl:mixin:APP:lithium.mixins.json:world.inline_height.WorldChunkMixin,pl:mixin:APP:lootr.mixins.json:MixinLevelChunk,pl:mixin:APP:gtceu.mixins.json:ChunkMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_6933_(Level.java:219) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.level.Level.m_7731_(Level.java:196) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.item.BlockItem.m_7429_(BlockItem.java:163) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:puzzleslib.common.mixins.json:accessor.BlockItemAccessor,pl:mixin:APP:quark.mixins.json:BlockItemMixin,pl:mixin:APP:quark.mixins.json:accessor.AccessorBlockItem,pl:mixin:A}
	at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:68) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:puzzleslib.common.mixins.json:accessor.BlockItemAccessor,pl:mixin:APP:quark.mixins.json:BlockItemMixin,pl:mixin:APP:quark.mixins.json:accessor.AccessorBlockItem,pl:mixin:A}
	at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:puzzleslib.common.mixins.json:accessor.BlockItemAccessor,pl:mixin:APP:quark.mixins.json:BlockItemMixin,pl:mixin:APP:quark.mixins.json:accessor.AccessorBlockItem,pl:mixin:A}
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:585) ~[forge-1.20.1-47.3.11-universal.jar%23490!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.hammerlib.json:ForgeHooksMixin,pl:mixin:APP:lootjs-forge.mixins.json:ForgeHooksMixin,pl:mixin:APP:nuclearcraft.mixins.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:245) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:mixins.hammerlib.json:ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:fastsuite.mixins.json:ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:355) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1055) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.forge_vehicle_packets.ServerGamePacketListenerImplMixin,pl:mixin:APP:forgivingvoid.mixins.json:ServerGamePacketListenerImplAccessor,pl:mixin:APP:badpackets.mixins.json:MixinServerGamePacketListenerImpl,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinServerGamePacketListenerImpl,pl:mixin:APP:hangglider.common.mixins.json:accessor.ServerGamePacketListenerImplAccessor,pl:mixin:APP:toofast.mixins.json:MixinServerNetPlayHandler,pl:mixin:APP:gtceu.mixins.json:ServerGamePacketListenerImplAccessor,pl:mixin:APP:quark.mixins.json:accessor.AccessorServerGamePacketListener,pl:mixin:APP:connectivity.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ichunutil.mixins.json:MinecraftServerAccessorMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:waterframes.mixin.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ichunutil.mixins.json:MinecraftServerAccessorMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:waterframes.mixin.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ichunutil.mixins.json:MinecraftServerAccessorMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:waterframes.mixin.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ichunutil.mixins.json:MinecraftServerAccessorMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:waterframes.mixin.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ichunutil.mixins.json:MinecraftServerAccessorMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:waterframes.mixin.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ichunutil.mixins.json:MinecraftServerAccessorMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:waterframes.mixin.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23485!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ichunutil.mixins.json:MinecraftServerAccessorMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:waterframes.mixin.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}
```

**Comment by Xefyr0** [comment]
Unable to reproduce.
Based on the log you provided, it may be an issue with your Java install or hardware rather than Monifactory.
It may have also been fixed since you made this report.
