### ISSUE TITLE
[Bug]: Exponential time consumption on world load

### ISSUE THREAD

**Issue by riking** [ThePansmith/Monifactory#992]
### Issue Summary

World loading eventually takes longer and longer, appearing to hang.

v0.9.7

https://mclo.gs/QZsdxGB

### Reproduction steps

Hop back and forth between overworld and void world using `/home` several times.

I suspect this has also been happening on repeated Save & Quit to Title + enter singleplayer.

### Relevant log output

```shell
[22:26:31] [ModernFix integrated server watchdog/ERROR] [or.em.mo.wo.IntegratedWatchdog/]: A single server tick has taken 42523, more than 40000 milliseconds


[22:27:24] [ModernFix integrated server watchdog/ERROR] [or.em.mo.wo.IntegratedWatchdog/]: Thread Dump:
"Render thread" prio=10 Id=1 RUNNABLE
	at java.base@17.0.11/java.lang.ClassLoader.defineClass0(Native Method)
	at java.base@17.0.11/java.lang.System$2.defineClass(System.java:2311)
...
	at java.base@17.0.11/java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCode(InvokerBytecodeGenerator.java:752)
	at java.base@17.0.11/java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:854)
...
	at java.base@17.0.11/java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:379)
	at java.base@17.0.11/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:885)
	at java.base@17.0.11/java.lang.invoke.MethodHandle.asType(MethodHandle.java:869)
	at java.base@17.0.11/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at TRANSFORMER/architectury@9.2.14/dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at TRANSFORMER/architectury@9.2.14/dev.architectury.event.EventFactory$2.handleInvocation(EventFactory.java:81)
...
	at TRANSFORMER/architectury@9.2.14/dev.architectury.event.forge.__EventHandlerImplCommon_event_EntityJoinLevelEvent.invoke(.dynamic)
...
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.ClientLevel.m_104739_(ClientLevel.java:336)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.ClientLevel.m_104627_(ClientLevel.java:332)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.ClientPacketListener.m_6771_(ClientPacketListener.java:452)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ClientboundAddEntityPacket.m_5797_(ClientboundAddEntityPacket.java:99)
...
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
...
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```
```
[22:29:56] [Server thread/INFO] [minecraft/MinecraftServer]: ***** left the game
[22:29:57] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: Stopping singleplayer server as player logged out
[22:29:57] [Server thread/INFO] [ne.cr.ft.FTBBackups/]: Shutdown Complete
[22:29:57] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[22:29:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[22:29:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
Log uploaded to: https://mclo.gs/QZsdxGB
Process was killed by user.
```

**Comment by riking** [comment]
I eventually managed to load into the world, but failed to save & quit.

jstack reports the Server thread is hung in `getChunkBlocking`:

```
"Worker-Main-133" #9623 daemon prio=1 os_prio=0 cpu=8760.35ms elapsed=7651.48s tid=0x00007fbf5c08fac0 nid=0x91e0e waiting on condition  [0x00007fc122dfd000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.11/Native Method)
        - parking to wait for  <0x00000007c58e21f8> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(java.base@17.0.11/LockSupport.java:211)
        at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.11/CompletableFuture.java:1864)
        at java.util.concurrent.ForkJoinPool.compensatedBlock(java.base@17.0.11/ForkJoinPool.java:3451)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.11/ForkJoinPool.java:3434)
        at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.11/CompletableFuture.java:1898)
        at java.util.concurrent.CompletableFuture.join(java.base@17.0.11/CompletableFuture.java:2117)
        at net.minecraft.server.level.ServerChunkCache.getChunkOffThread(minecraft@1.20.1/ServerChunkCache.java:1676)
        at net.minecraft.server.level.ServerChunkCache.m_7587_(minecraft@1.20.1/ServerChunkCache.java:1641)
        at net.minecraft.world.level.Level.m_6522_(minecraft@1.20.1/Level.java:187)
        at net.minecraft.world.level.Level.m_46865_(minecraft@1.20.1/Level.java:3541)
        at net.minecraftforge.common.extensions.IForgeBlockGetter.getExistingBlockEntity(forge@47.3.7/IForgeBlockGetter.java:39)
        at com.enderio.core.common.compat.FlywheelCompat.getExistingBlockEntity(enderio@6.2.0-beta/FlywheelCompat.java:16)
        at com.enderio.machines.common.block.MachineBlock.getLightEmission(enderio@6.2.0-beta/MachineBlock.java:150)
        at net.minecraftforge.common.extensions.IForgeBlockState.getLightEmission(forge@47.3.7/IForgeBlockState.java:79)
        at net.minecraft.world.level.lighting.BlockLightEngine.m_284436_(minecraft@1.20.1/BlockLightEngine.java:108)
        at net.minecraft.world.level.lighting.BlockLightEngine.m_75858_(minecraft@1.20.1/BlockLightEngine.java:29)
        at net.minecraft.world.level.lighting.LightEngine.m_9323_(minecraft@1.20.1/LightEngine.java:143)
        at net.minecraft.world.level.lighting.LevelLightEngine.m_9323_(minecraft@1.20.1/LevelLightEngine.java:53)
        at net.minecraft.server.level.ThreadedLevelLightEngine.m_9366_(minecraft@1.20.1/ThreadedLevelLightEngine.java:187)
        at net.minecraft.server.level.ThreadedLevelLightEngine.m_215156_(minecraft@1.20.1/ThreadedLevelLightEngine.java:166)
        at net.minecraft.server.level.ThreadedLevelLightEngine$$Lambda$28529/0x00007fc1c31e6db8.run(minecraft@1.20.1/Unknown Source)
        at net.minecraft.util.thread.ProcessorMailbox.m_18759_(minecraft@1.20.1/ProcessorMailbox.java:91)
        at net.minecraft.util.thread.ProcessorMailbox.m_18747_(minecraft@1.20.1/ProcessorMailbox.java:146)
        at net.minecraft.util.thread.ProcessorMailbox.run(minecraft@1.20.1/ProcessorMailbox.java:102)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(java.base@17.0.11/ForkJoinTask.java:1395)
        at java.util.concurrent.ForkJoinTask.doExec(java.base@17.0.11/ForkJoinTask.java:373)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@17.0.11/ForkJoinPool.java:1182)
        at java.util.concurrent.ForkJoinPool.scan(java.base@17.0.11/ForkJoinPool.java:1655)
        at java.util.concurrent.ForkJoinPool.runWorker(java.base@17.0.11/ForkJoinPool.java:1622)
        at java.util.concurrent.ForkJoinWorkerThread.run(java.base@17.0.11/ForkJoinWorkerThread.java:165)
```
```
"Server thread" #12505 prio=5 os_prio=0 cpu=1065588.05ms elapsed=4776.01s tid=0x00007fbea4adf940 nid=0x9428c waiting on condition  [0x00007fc1b81ed000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.11/Native Method)
        - parking to wait for  <0x00000007298bb630> (a java.lang.String)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.11/LockSupport.java:252)
        at net.minecraft.util.thread.BlockableEventLoop.m_5667_(minecraft@1.20.1/BlockableEventLoop.java:521)
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(minecraft@1.20.1/BlockableEventLoop.java:141)
        at net.minecraft.server.level.ServerChunkCache.getChunkBlocking(minecraft@1.20.1/ServerChunkCache.java:1772)
        at net.minecraft.server.level.ServerChunkCache.m_7587_(minecraft@1.20.1/ServerChunkCache.java:1664)
        at net.minecraft.server.level.ServerChunkCache.md0cb100$lambda$getChunkOffThread$0$0(minecraft@1.20.1/ServerChunkCache.java:1676)
        at net.minecraft.server.level.ServerChunkCache$$Lambda$29566/0x00007fc1c3331c88.get(minecraft@1.20.1/Unknown Source)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(java.base@17.0.11/CompletableFuture.java:1768)
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(minecraft@1.20.1/BlockableEventLoop.java:156)
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(minecraft@1.20.1/ServerChunkCache.java:541)
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(minecraft@1.20.1/BlockableEventLoop.java:130)
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(minecraft@1.20.1/ServerChunkCache.java:549)
        at net.minecraft.server.level.ServerChunkCache.m_8466_(minecraft@1.20.1/ServerChunkCache.java:269)
        at net.minecraft.server.MinecraftServer.m_129961_(minecraft@1.20.1/MinecraftServer.java:758)
        at net.minecraft.server.MinecraftServer.m_7245_(minecraft@1.20.1/MinecraftServer.java:747)
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(minecraft@1.20.1/BlockableEventLoop.java:115)
        at net.minecraft.server.MinecraftServer.m_130012_(minecraft@1.20.1/MinecraftServer.java:732)
        at net.minecraft.server.MinecraftServer.m_7041_(minecraft@1.20.1/MinecraftServer.java:581)
        at net.minecraft.client.server.IntegratedServer.m_7041_(minecraft@1.20.1/IntegratedServer.java:187)
        at net.minecraft.server.MinecraftServer.m_130011_(minecraft@1.20.1/MinecraftServer.java:689)
        at net.minecraft.server.MinecraftServer.m_206580_(minecraft@1.20.1/MinecraftServer.java:251)
        at net.minecraft.server.MinecraftServer$$Lambda$28205/0x00007fc1c3143448.run(minecraft@1.20.1/Unknown Source)
        at java.lang.Thread.run(java.base@17.0.11/Thread.java:840)
```

**Comment by riking** [comment]
I need to update the pack and try to reproduce.

**Comment by riking** [comment]
Upon updating the pack, restoring a backup, loading in, opening questbook, and nearly immediately S&Qing, it appears to hang again:

```
"Worker-Main-4" #126 daemon prio=1 os_prio=0 cpu=230.93ms elapsed=502.80s tid=0x00007f8700163080 nid=0x9ad6d waiting on condition  [0x00007f87bd3fd000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.11/Native Method)
        - parking to wait for  <0x00000007fd6494d8> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(java.base@17.0.11/LockSupport.java:211)
        at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.11/CompletableFuture.java:1864)
        at java.util.concurrent.ForkJoinPool.compensatedBlock(java.base@17.0.11/ForkJoinPool.java:3451)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.11/ForkJoinPool.java:3434)
        at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.11/CompletableFuture.java:1898)
        at java.util.concurrent.CompletableFuture.join(java.base@17.0.11/CompletableFuture.java:2117)
        at net.minecraft.server.level.ServerChunkCache.getChunkOffThread(minecraft@1.20.1/ServerChunkCache.java:1676)
        at net.minecraft.server.level.ServerChunkCache.m_7587_(minecraft@1.20.1/ServerChunkCache.java:1641)
        at net.minecraft.world.level.Level.m_6522_(minecraft@1.20.1/Level.java:187)
        at net.minecraft.world.level.Level.m_46865_(minecraft@1.20.1/Level.java:3541)
        at net.minecraftforge.common.extensions.IForgeBlockGetter.getExistingBlockEntity(forge@47.3.7/IForgeBlockGetter.java:39)
        at com.enderio.core.common.compat.FlywheelCompat.getExistingBlockEntity(enderio@6.2.1-beta/FlywheelCompat.java:16)
        at com.enderio.machines.common.block.MachineBlock.getLightEmission(enderio@6.2.1-beta/MachineBlock.java:150)
        at net.minecraftforge.common.extensions.IForgeBlockState.getLightEmission(forge@47.3.7/IForgeBlockState.java:79)
        at net.minecraft.world.level.lighting.BlockLightEngine.m_284436_(minecraft@1.20.1/BlockLightEngine.java:108)
        at net.minecraft.world.level.lighting.BlockLightEngine.m_284321_(minecraft@1.20.1/BlockLightEngine.java:88)
        at net.minecraft.world.level.lighting.LightEngine.m_284399_(minecraft@1.20.1/LightEngine.java:182)
        at net.minecraft.world.level.lighting.LightEngine.m_9323_(minecraft@1.20.1/LightEngine.java:149)
        at net.minecraft.world.level.lighting.LevelLightEngine.m_9323_(minecraft@1.20.1/LevelLightEngine.java:53)
        at net.minecraft.server.level.ThreadedLevelLightEngine.m_9366_(minecraft@1.20.1/ThreadedLevelLightEngine.java:187)
        at net.minecraft.server.level.ThreadedLevelLightEngine.m_215156_(minecraft@1.20.1/ThreadedLevelLightEngine.java:166)
        at net.minecraft.server.level.ThreadedLevelLightEngine$$Lambda$28528/0x00007f883b211810.run(minecraft@1.20.1/Unknown Source)
        at net.minecraft.util.thread.ProcessorMailbox.m_18759_(minecraft@1.20.1/ProcessorMailbox.java:91)
        at net.minecraft.util.thread.ProcessorMailbox.m_18747_(minecraft@1.20.1/ProcessorMailbox.java:146)
        at net.minecraft.util.thread.ProcessorMailbox.run(minecraft@1.20.1/ProcessorMailbox.java:102)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(java.base@17.0.11/ForkJoinTask.java:1395)
        at java.util.concurrent.ForkJoinTask.doExec(java.base@17.0.11/ForkJoinTask.java:373)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@17.0.11/ForkJoinPool.java:1182)
        at java.util.concurrent.ForkJoinPool.scan(java.base@17.0.11/ForkJoinPool.java:1655)
        at java.util.concurrent.ForkJoinPool.runWorker(java.base@17.0.11/ForkJoinPool.java:1622)
        at java.util.concurrent.ForkJoinWorkerThread.run(java.base@17.0.11/ForkJoinWorkerThread.java:165)
```
progress does appear to be happening, since the wait address is different:
```
"Worker-Main-4" #126 daemon prio=1 os_prio=0 cpu=230.93ms elapsed=591.75s tid=0x00007f8700163080 nid=0x9ad6d waiting on condition  [0x00007f87bd3fd000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.11/Native Method)
        - parking to wait for  <0x00000007c42ef490> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(java.base@17.0.11/LockSupport.java:211)
        at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.11/CompletableFuture.java:1864)
        at java.util.concurrent.ForkJoinPool.compensatedBlock(java.base@17.0.11/ForkJoinPool.java:3451)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.11/ForkJoinPool.java:3434)
        at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.11/CompletableFuture.java:1898)
        at java.util.concurrent.CompletableFuture.join(java.base@17.0.11/CompletableFuture.java:2117)
        at net.minecraft.server.level.ServerChunkCache.getChunkOffThread(minecraft@1.20.1/ServerChunkCache.java:1676)
        at net.minecraft.server.level.ServerChunkCache.m_7587_(minecraft@1.20.1/ServerChunkCache.java:1641)
        at net.minecraft.world.level.Level.m_6522_(minecraft@1.20.1/Level.java:187)
        at net.minecraft.world.level.Level.m_46865_(minecraft@1.20.1/Level.java:3541)
        at net.minecraftforge.common.extensions.IForgeBlockGetter.getExistingBlockEntity(forge@47.3.7/IForgeBlockGetter.java:39)
        at com.enderio.core.common.compat.FlywheelCompat.getExistingBlockEntity(enderio@6.2.1-beta/FlywheelCompat.java:16)
        at com.enderio.machines.common.block.MachineBlock.getLightEmission(enderio@6.2.1-beta/MachineBlock.java:150)
        at net.minecraftforge.common.extensions.IForgeBlockState.getLightEmission(forge@47.3.7/IForgeBlockState.java:79)
        at net.minecraft.world.level.lighting.BlockLightEngine.m_284436_(minecraft@1.20.1/BlockLightEngine.java:108)
        at net.minecraft.world.level.lighting.BlockLightEngine.m_284321_(minecraft@1.20.1/BlockLightEngine.java:88)
        at net.minecraft.world.level.lighting.LightEngine.m_284399_(minecraft@1.20.1/LightEngine.java:182)
        at net.minecraft.world.level.lighting.LightEngine.m_9323_(minecraft@1.20.1/LightEngine.java:149)
        at net.minecraft.world.level.lighting.LevelLightEngine.m_9323_(minecraft@1.20.1/LevelLightEngine.java:53)
        at net.minecraft.server.level.ThreadedLevelLightEngine.m_9366_(minecraft@1.20.1/ThreadedLevelLightEngine.java:187)
        at net.minecraft.server.level.ThreadedLevelLightEngine.m_215156_(minecraft@1.20.1/ThreadedLevelLightEngine.java:166)
        at net.minecraft.server.level.ThreadedLevelLightEngine$$Lambda$28528/0x00007f883b211810.run(minecraft@1.20.1/Unknown Source)
        at net.minecraft.util.thread.ProcessorMailbox.m_18759_(minecraft@1.20.1/ProcessorMailbox.java:91)
        at net.minecraft.util.thread.ProcessorMailbox.m_18747_(minecraft@1.20.1/ProcessorMailbox.java:146)
        at net.minecraft.util.thread.ProcessorMailbox.run(minecraft@1.20.1/ProcessorMailbox.java:102)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(java.base@17.0.11/ForkJoinTask.java:1395)
        at java.util.concurrent.ForkJoinTask.doExec(java.base@17.0.11/ForkJoinTask.java:373)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@17.0.11/ForkJoinPool.java:1182)
        at java.util.concurrent.ForkJoinPool.scan(java.base@17.0.11/ForkJoinPool.java:1655)
        at java.util.concurrent.ForkJoinPool.runWorker(java.base@17.0.11/ForkJoinPool.java:1622)
        at java.util.concurrent.ForkJoinWorkerThread.run(java.base@17.0.11/ForkJoinWorkerThread.java:165)
```

```
"Server thread" #199 prio=5 os_prio=0 cpu=46499.10ms elapsed=413.62s tid=0x00007f851c337810 nid=0x9b2cc runnable  [0x00007f87b28fd000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.11/Native Method)
        - parking to wait for  <0x0000000729c82748> (a java.lang.String)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.11/LockSupport.java:252)
        at net.minecraft.util.thread.BlockableEventLoop.m_5667_(minecraft@1.20.1/BlockableEventLoop.java:521)
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(minecraft@1.20.1/BlockableEventLoop.java:141)
        at net.minecraft.server.level.ServerChunkCache.getChunkBlocking(minecraft@1.20.1/ServerChunkCache.java:1772)
        at net.minecraft.server.level.ServerChunkCache.m_7587_(minecraft@1.20.1/ServerChunkCache.java:1664)
        at net.minecraft.server.level.ServerChunkCache.md68291a$lambda$getChunkOffThread$0$0(minecraft@1.20.1/ServerChunkCache.java:1676)
        at net.minecraft.server.level.ServerChunkCache$$Lambda$29558/0x00007f883b35c000.get(minecraft@1.20.1/Unknown Source)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(java.base@17.0.11/CompletableFuture.java:1768)
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(minecraft@1.20.1/BlockableEventLoop.java:156)
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(minecraft@1.20.1/ServerChunkCache.java:541)
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(minecraft@1.20.1/BlockableEventLoop.java:130)
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(minecraft@1.20.1/ServerChunkCache.java:549)
        at net.minecraft.server.level.ServerChunkCache.m_8466_(minecraft@1.20.1/ServerChunkCache.java:269)
        at net.minecraft.server.MinecraftServer.m_129961_(minecraft@1.20.1/MinecraftServer.java:758)
        at net.minecraft.server.MinecraftServer.m_7245_(minecraft@1.20.1/MinecraftServer.java:747)
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(minecraft@1.20.1/BlockableEventLoop.java:115)
        at net.minecraft.server.MinecraftServer.m_130012_(minecraft@1.20.1/MinecraftServer.java:732)
        at net.minecraft.server.MinecraftServer.m_7041_(minecraft@1.20.1/MinecraftServer.java:581)
        at net.minecraft.client.server.IntegratedServer.m_7041_(minecraft@1.20.1/IntegratedServer.java:187)
        at net.minecraft.server.MinecraftServer.m_130011_(minecraft@1.20.1/MinecraftServer.java:689)
        at net.minecraft.server.MinecraftServer.m_206580_(minecraft@1.20.1/MinecraftServer.java:251)
        at net.minecraft.server.MinecraftServer$$Lambda$28195/0x00007f883b168000.run(minecraft@1.20.1/Unknown Source)
        at java.lang.Thread.run(java.base@17.0.11/Thread.java:840)
```

There is a second thread waiting on the same object as the Server thread:

```
"Sound engine" #292 daemon prio=10 os_prio=0 cpu=0.25ms elapsed=261.21s tid=0x00007f851cc1dc30 nid=0x9b543 waiting on condition  [0x00007f87a5dfe000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.11/Native Method)
        - parking to wait for  <0x0000000729c82748> (a java.lang.String)
        at java.util.concurrent.locks.LockSupport.park(java.base@17.0.11/LockSupport.java:211)
        at net.minecraft.client.sounds.SoundEngineExecutor.m_5667_(minecraft@1.20.1/SoundEngineExecutor.java:49)
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(minecraft@1.20.1/BlockableEventLoop.java:141)
        at net.minecraft.client.sounds.SoundEngineExecutor.m_120336_(minecraft@1.20.1/SoundEngineExecutor.java:42)
        at net.minecraft.client.sounds.SoundEngineExecutor$$Lambda$18902/0x00007f883a5f5218.run(minecraft@1.20.1/Unknown Source)
        at java.lang.Thread.run(java.base@17.0.11/Thread.java:840)
```

**Comment by MightyPiggie** [comment]
You only have a maximum of 4gb of ram allocated. Together with the not that fast system already could definitely cause this. Any chance you could increase the ram to at least 6gb and preferably even 8gb or more?

**Comment by riking** [comment]
Oh wow, completely forgot to increase that. Yeah that's quite likely to be the problem!
